definitions:
  controller.GetCampaignResponse:
    properties:
      item:
        $ref: '#/definitions/models.CampaignDto'
    type: object
  models.CampaignDto:
    properties:
      campaignId:
        type: integer
      campaignName:
        type: string
    type: object
info:
  contact:
    email: mahmutozben61@gmail.com
  description: Basket-Discount API
  title: Basket-Discount API
  version: "1.0"
paths:
  /api/v1/discount/campaign/{campaignId}:
    get:
      parameters:
      - description: campaignId valid
        in: path
        name: campaignId
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.GetCampaignResponse'
        "404":
          description: Not Found
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get campaign
      tags:
      - discount
swagger: "2.0"
